version: '3.8'

services:
  file-storage-db:
    image: postgres:15
    container_name: file-storage-db
    restart: always
    environment:
      POSTGRES_DB: definex.file_storage_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - file_storage_db_data:/var/lib/postgresql/data

  user-auth-db:
    image: postgres:15
    container_name: user-auth-db
    restart: always
    environment:
      POSTGRES_DB: definex.user_auth_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - user_auth_db_data:/var/lib/postgresql/data

volumes:
  file_storage_db_data:
    driver: local
  user_auth_db_data:
    driver: local
