version: '3.8'

services:
  eureka-server:
    build:
      context: ./eureka-server # Ensure this is the correct path to your Eureka server project
      dockerfile: Dockerfile
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"
    environment:
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false

  postgres-file-storage:
    image: postgres:15
    container_name: file-storage-db
    restart: always
    environment:
      POSTGRES_DB: definex.file_storage_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_file_storage_data:/var/lib/postgresql/data

  postgres-auth-service:
    image: postgres:15
    container_name: auth-service-db
    restart: always
    environment:
      POSTGRES_DB: definex.user_authentication_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_service_data:/var/lib/postgresql/data

volumes:
  postgres_file_storage_data:
    driver: local
  postgres_auth_service_data:
    driver: local
