version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: file-storage-db
    restart: always
    environment:
      POSTGRES_DB: definex.file_storage_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
